name: packages
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - imageio
  - natsort
  - astropy
  - scipy
  - six
  - numba
  - scikit-image
  - scikit-learn
  - autolens
  - lenstronomy
  - corner
  - autofit 
  - pip:
    - colossus
