name: packages
channels:
  - conda-forge
dependencies:
  - numpy 
  - matplotlib-base
  - imageio
  - natsort
  - astropy
  - scipy
  - six
  - numba
  - scikit-image
  - scikit-learn
  - lenstronomy
  - corner
  - pip
  - pip:
    - colossus
    - autofit
    - autolens
